[project]
name = "discord-llm-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.32.5",
    "typer>=0.21.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.format]
indent-style = "tab"
